CREATE TABLE IF NOT EXISTS decks (
    id         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    main_name       VARCHAR(128) NOT NULL,
    sub_name    VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);